== What you need to run Grabbit.

* Supported AEM/CQ version per below
* One-time installation of a system Fragment Bundle is needed. It can be found link:https://bintray.com/artifact/download/twcable/aem/dependencies/Sun-Misc-Fragment-Bundle-1.0.0.zip[here]
* If running AEM 6.2+ with the AEM Deserialization Firewall enabled, link:https://bintray.com/twcable/aem/download_file?file_path=dependencies%2FGrabbit-Deserialization-Firewall-Configuration-1.0.zip[this package] is required in order
for Grabbit to work. If running the deserialization firewall with custom blacklist/whitelist rules, check out the package description to gather which additional paths will need to be considered.
* In Addition to the AEM Deserialization Firewall package, you would need to install link:https://bintray.com/artifact/download/twcable/aem/dependencies/Grabbit-Apache-Sling-Login-Whitelist-1.0.zip[this] to have the grabbit bundle be whitelisted with Apache Sling Login Admin.

== Below details AEM version support for the various releases of Grabbit.
```
   v7.x - AEM 6.1 and AEM 6.2 and AEM 6.3
   v5.x - AEM 6.1
   v4.x - AEM 6.1
   v3.x - CQ 5.6 and AEM 6.0
   v2.x - CQ 5.6
```
We follow link:http://semver.org/[semantic versioning]. Installation of different major versions between machines are unsupported, and likely incompatible.

Active development is on the "master" branch. Security patches and the like are sometimes back-ported to prior versions.

Of course pull-requests are happily accepted for those that would like to submit things like back-porting features for AEM 5.6, etc.

image:https://api.bintray.com/packages/twcable/aem/Grabbit/images/download.svg[title = "Download", link = "https://bintray.com/twcable/aem/Grabbit/_latestVersion"]
